SRMS/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SRMS.Models;

namespace SRMS.Controllers
{
    public class ClassController : Controller
    {
        private readonly ClassDbContext clsDb;

        public ClassController(ClassDbContext ClsDb)
        {
           this.clsDb = ClsDb;
        }
        public async Task<IActionResult> ClassIndex()
        {
            var clsData = await clsDb.Classes.ToListAsync();
            return View(clsData);
        }
        public async Task<IActionResult> AddClass()
        {
         
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddClass(ClassModel Cls)
        {
            if (ModelState.IsValid)
            {
                var clsData = await clsDb.Classes.AddAsync(Cls);
                await clsDb.SaveChangesAsync();
                TempData["Success Message"] = "Record Create Successfully";
                
            }
            return View();
        }
        [HttpGet("/Class/UpdateClass/{Id}")]
        public async Task <IActionResult> UpdateClass(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var clsData = await clsDb.Classes.FirstOrDefaultAsync(s => s.Id == Id);

            if (clsData == null)
            {
                return NotFound();
            }

            return View(clsData);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateClass(int Id, ClassModel cls)
        {
            if (Id != cls.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                clsDb.Classes.Update(cls);
                await clsDb.SaveChangesAsync();
                return RedirectToAction("ClassIndex");
            }

            return View(cls);
        }
    }
}

SRMS/Controllers/StudentController.cs
//using Microsoft.AspNetCore.Mvc;
//using SRMS.Models;
//using System.Runtime.Intrinsics.Arm;

//namespace SRMS.Controllers
//{
//    public class StudentController : Controller
//    {
//        private readonly StudentDbContext stdDb;

//        public StudentController(StudentDbContext stdDb )
//        {
//            this.stdDb = stdDb;
//        }
//        public IActionResult StudentIndex()
//        {
//            var stdData = stdDb.Students.ToList();
//            return View(stdData);
//        }
//        public IActionResult AddStudent()
//        {
//            return View();
//        }
//        [HttpPost]
//        public async Task<IActionResult> AddStudent(StudentModel StdM)
//        {
//            if (ModelState.IsValid)
//            {
//                await stdDb.Students.AddAsync(StdM);
//                await stdDb.SaveChangesAsync();
//                TempData["SuccessMessage"] = "Record Create successfully!";
//                ModelState.Clear();
//             return RedirectToAction("StudentIndex");
//            }
//            return View();
//        }
//        [Route("/Student/EditStudent/{RollNo}")]
//        public IActionResult StudentDetails(int? RollNo)
//        {
//            // Fetch the student from the database based on the provided RollNo
//            var student = stdDb.Students.FirstOrDefault(s => s.RollNo == RollNo);

//            // Check if the student is found
//            if (student == null)
//            {
//                return NotFound(); // Or handle the case where the student is not found
//            }

//            return View(student); // Pass the student data to the view
//        }
//        public async Task<IActionResult> UpdateStudent(int RollNo)
//        {
//            if (RollNo == null || stdDb.Students == null)
//            {
//                return NotFound();
//            }

//            var stdData = await stdDb.Students.FindAsync(RollNo);
//            if(stdData == null)
//            {
//                return NotFound();
//            }
//            return View(stdData);
//        }
//        [HttpPost]
//        public async Task<IActionResult>UpdateStudent(int rollNo,StudentModel std)
//        {
//            if (rollNo ! == std.RollNo)
//            {
//                return NotFound();
//            }
//            if (ModelState.IsValid)
//            {
//                stdDb.Students.Update(std);
//                await stdDb.SaveChangesAsync();
//                return RedirectToAction("StudentIndex");
//            }
//            return View(std); 
//        }
//    }
//}

using Microsoft.AspNetCore.Mvc;
using SRMS.Models;
using System.Linq;
using System.Threading.Tasks;

namespace SRMS.Controllers
{
    public class StudentController : Controller
    {
        private readonly StudentDbContext stdDb;

        public StudentController(StudentDbContext stdDb)
        {
            this.stdDb = stdDb;
        }

        public IActionResult StudentIndex()
        {
            var stdData = stdDb.Students.ToList();
            return View(stdData);
        }


        [HttpGet("/Student/StudentDetails/{RollNo}")]
        public IActionResult StudentDetails(int? RollNo)
        {
            if (RollNo == null)
            {
                return NotFound();
            }

            var stdData = stdDb.Students.FirstOrDefault(s => s.RollNo == RollNo);

            if (stdData == null)
            {
                return NotFound();
            }

            return View(stdData);
        }



        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddStudent(StudentModel StdM)
        {
            if (ModelState.IsValid)
            {
                await stdDb.Students.AddAsync(StdM);
                await stdDb.SaveChangesAsync();
                TempData["SuccessMessage"] = "Record created successfully!";
                ModelState.Clear();
                return RedirectToAction("StudentIndex");
            }
            return View();
        }

        [HttpGet("/Student/UpdateStudent/{RollNo}")]
        public IActionResult UpdateStudent(int? RollNo)
        {
            if (RollNo == null)
            {
                return NotFound();
            }

            var stdData = stdDb.Students.FirstOrDefault(s => s.RollNo == RollNo);

            if (stdData == null)
            {
                return NotFound();
            }

            return View(stdData);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStudent(int rollNo, StudentModel std)
        {
            if (rollNo != std.RollNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                stdDb.Students.Update(std);
                await stdDb.SaveChangesAsync();
                return RedirectToAction("StudentIndex");
            }

            return View(std);
        }
    }
}

SRMS/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SRMS.Models;

namespace SRMS.Controllers
{
    public class SubjectController : Controller
    {
        private readonly SubjectDbContext _context;

        public SubjectController(SubjectDbContext context)
        {
            _context = context;
        }

        // GET: Subject
        public async Task<IActionResult> Index()
        {
              return _context.Subjects != null ? 
                          View(await _context.Subjects.ToListAsync()) :
                          Problem("Entity set 'SubjectDbContext.Subjects'  is null.");
        }

        // GET: Subject/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subjectModel = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subjectModel == null)
            {
                return NotFound();
            }

            return View(subjectModel);
        }

        // GET: Subject/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subject/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Std,SubjectName,SubjectCode,Description")] SubjectModel subjectModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subjectModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(subjectModel);
        }

        // GET: Subject/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subjectModel = await _context.Subjects.FindAsync(id);
            if (subjectModel == null)
            {
                return NotFound();
            }
            return View(subjectModel);
        }

        // POST: Subject/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Std,SubjectName,SubjectCode,Description")] SubjectModel subjectModel)
        {
            if (id != subjectModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subjectModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectModelExists(subjectModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subjectModel);
        }

        // GET: Subject/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subjectModel = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subjectModel == null)
            {
                return NotFound();
            }

            return View(subjectModel);
        }

        // POST: Subject/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Subjects == null)
            {
                return Problem("Entity set 'SubjectDbContext.Subjects'  is null.");
            }
            var subjectModel = await _context.Subjects.FindAsync(id);
            if (subjectModel != null)
            {
                _context.Subjects.Remove(subjectModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectModelExists(int id)
        {
          return (_context.Subjects?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SRMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SRMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SRMS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    


  
</head>
<body class="d-flex flex-column h-100">
    <div class=".bg-dark.bg-gradient">
        <header >
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <h4 class="bg-dark text-white p-4"><i class="fa-solid fa-school"></i>  Student Result Management System</h4>
                <div class="container justify-content-between">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav me-auto" style="font-size: x-large">
                            <li class="nav-item mx-2">
                                <a class="nav-link" asp-controller="Home" asp-action="Dashboard"><i class="fa-solid fa-house"></i> Home</a>
                            </li>
                            <li class="nav-item dropdown mx-2">
                                <a class="nav-link dropdown-toggle" id="studentDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-graduation-cap"></i> Student
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="studentDropdown">
                                    <li><a class="dropdown-item" asp-controller="Student" asp-action="StudentIndex">Student Index</a></li>
                                    <li><a class="dropdown-item" asp-controller="Student" asp-action="AddStudent">Add Student</a></li>
                                    <!-- Add more student-related links as needed -->
                                </ul>
                            </li>
                            <li class="nav-item dropdown mx-2 ">
                                <a class="nav-link dropdown-toggle" href="ClassIndex" id="classDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-people-roof"></i>  Class
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="classDropdown">
                                    <li><a class="dropdown-item" asp-controller="Class" asp-action="ClassIndex">Class Index</a></li>
                                    <li><a class="dropdown-item" asp-controller="Class" asp-action="AddClass">Add Class</a></li>
                                    <!-- Add more class-related links as needed -->
                                </ul>
                            </li>
                            <li class="nav-item dropdown mx-2">
                                <a class="nav-link dropdown-toggle" href="#" id="subjectDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-book-open"></i> Subject
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="subjectDropdown">
                                    <li><a class="dropdown-item" asp-controller="Subject" asp-action="Index">Subject Index</a></li>
                                    <li><a class="dropdown-item" asp-controller="Subject" asp-action="Create">Add Subject</a></li>
                                    <!-- Add more subject-related links as needed -->
                                </ul>
                            </li>
                            <li class="nav-item dropdown mx-2">
                                <a class="nav-link dropdown-toggle" href="#" id="resultDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-square-poll-horizontal"></i> Result
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="resultDropdown">
                                    <li><a class="dropdown-item" asp-controller="Index" asp-action="ResultIndex">Result Index</a></li>
                                    <li><a class="dropdown-item" asp-controller="Index" asp-action="AddResult">Add Result</a></li>
                                    <!-- Add more result-related links as needed -->
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="d-flex justify-content-right">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown mx-2">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <h5>Welcome!</h5> <i class="fa-solid fa-user-tie"></i> @ViewBag.AdmSession
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                    <li><a class="dropdown-item" href="#">  <i class="fa-solid fa-user"></i> Profile</a></li>
                                    <li><a class="dropdown-item" href="#"> <i class="fa-solid fa-gear"></i> Settings </a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="AdminLogin"><i class="fa-solid fa-right-from-bracket"></i> Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                        <!-- Add your logo here -->
                        <!-- Example: <img src="path/to/logo.png" alt="Logo"> -->
                    </div>
                </div>
            </nav>
        </header>

        <main role="main">
            <div class="row">
                <div class="col-12">
                    @RenderBody()
                </div>
            </div>
        </main>
        <footer class ="text-muted">
            <p>&copy; 2024 Student Result Management System</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>